# NOTE: Look, don't touch. This file is managed by https://github.com/iheartradio/ds-gh-management

name: Manual
on:
  workflow_dispatch:

jobs:
  run_test:
    name: Job
    runs-on: ubuntu-22.04 
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: who am i in the runner?
        working-directory: "./airflow"
        run: bash ./test.sh
